# This workflow deployed the downloading dependencies needed for Nodes; triggered by someone push into github.

name: CI

on:
  push:
    branches: [ testing-workflows ]
  workflow_dispatch:
jobs:

## first job: check jsNode dependencies
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: "14.x"
      - run: npm install
        # install mocha test framework
      - run: npm install --global mocha
      - run: npm install --save-dev mocha
      - name: mocha test
        run: mocha $GITHUB_WORKSPACE/.github/workflows/test/*.js
  
