# This workflow deployed the downloading dependencies needed for Nodes; triggered by someone push into github.

name: CI

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: self-hosted

    strategy: 
        matrix:
            node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
            node-version: ${{ matrix.node-version }}
            
      - name: Install dependencies
        run: npm install
      - name: Build dependencies
        run: npm run build --if-present
      - name: Test dependencies
        run: npm test
            
            
